kairosdb:
  build: .
  command: /bin/bash -c "sleep 30; /opt/kairosdb/bin/kairosdb.sh run"
  ports:
   - "8080:8080"
   - "4242:4242"
  links:
   - cassandra
cassandra:
  image: jimthedev/cassandra
  hostname: cassandra
  ports:
    - "9042:9042"
    - "9160:9160"
